### ISSUE TITLE
Add Asset Storage library

### ISSUE THREAD

**Issue by cmin764** [robocorp/robo#30]
This MVP will implement the basic client support for interacting with the **Asset Storage** API.

### ToDo
- [x] New `robocorp.storage` package dealing with the assets in a similar way to Work Items.
- [x] Listing, creating, retrieving and deleting assets support.
- [x] Basic [**direct**] asset upload when saving data into the asset.
- [x] Basic documentation.
- [x] Simple real API sweet test skipped from CI.

### ⚠️ This first iteration won't include (destined for follow-up post-release work):
- Updating an asset name and its meta-data. (no upstream API support atm)
- Uploading payloads bigger than 6MB. (requires URL-based asset upload support in the library)
- Uploading assets of other types than text. (like JSON, bytes, files etc.)
- Working locally with assets. (requires the Adapter pattern which mimics the flow with local files)
- Detailed documentation aligned well with the rest of the library.
- Production-ready Portal example show-casing the usage.
- Extended atomic unit-tests with full coverage.
- Legacy `rpaframework` support with RF keywords. (see [comment](https://github.com/robocorp/robo/issues/30#issuecomment-1593726467) below)

**Comment by cmin764** [comment]
Once this is done, the next step is to wrap this functionality into RF keywords by adding `robocorp-storage` as a dependency into the `rpaframework` legacy library. (https://github.com/robocorp/rpaframework/issues/957)
